[package]

name = "geojson"
description = "Library for serializing the GeoJSON vector GIS file format"
version = "0.9.0"
authors = ["Corey Farwell <coreyf@rwell.org>",
           "Blake Grotewold <hello@grotewold.me>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/rust-geojson"
readme = "README.md"
documentation = "https://docs.rs/geojson/"
keywords = ["geojson", "gis", "json", "geo"]

[dependencies]
serde = "~1.0"
serde_json = "~1.0"
geo = "0.6"
num-traits = "0.1"
smallvec = { version = "0.6.0", features = ["serde"], optional = true }
